### ISSUE TITLE
Collector: database access exception

### ISSUE THREAD

**Issue by city-pulse** [city-pulse/mskpulse.backend#58]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "collector.py", line 79, in run
    exec_mysql(q, self.mysql)
  File "/home/ubuntu/backend/utilities.py", line 93, in exec_mysql
    result = query.Query(cmd)
  File "/usr/local/lib/python2.7/dist-packages/PySQLPool/PySQLQuery.py", line 75, in Query
    return self.query(query, args)
  File "/usr/local/lib/python2.7/dist-packages/PySQLPool/PySQLQuery.py", line 146, in query
    raise self.lastError
OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')
```

**Comment by city-pulse** [comment]
Should be fixed in 5e0dcb59710860e7ba39cbc5c5757d4e195c013c
