### ISSUE TITLE
Detector crashed

### ISSUE THREAD

**Issue by city-pulse** [city-pulse/mskpulse.backend#61]
```
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:79: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
Traceback (most recent call last):
  File "detector.py", line 376, in <module>
    detector.run()
  File "detector.py", line 85, in run
    self.merge_slices_to_events(slice_clusters)
  File "detector.py", line 342, in merge_slices_to_events
    new_event = Event(self.mysql, self.redis, self.tokenizer, self.morph, self.classifier, meta_slice)
  File "/home/ubuntu/backend/event.py", line 132, in __init__
    self.event_update()
  File "/home/ubuntu/backend/event.py", line 152, in event_update
    self.score_messages_by_text()
  File "/home/ubuntu/backend/event.py", line 428, in score_messages_by_text
    scores = index[dictionary.doc2bow(self.cores[deviation_threshold])]
  File "/usr/local/lib/python2.7/dist-packages/gensim/interfaces.py", line 218, in __getitem__
    result = self.get_similarities(query)
  File "/usr/local/lib/python2.7/dist-packages/gensim/similarities/docsim.py", line 560, in get_similarities
    query = matutils.sparse2full(query, self.num_features)
  File "/usr/local/lib/python2.7/dist-packages/gensim/matutils.py", line 209, in sparse2full
    result[list(doc)] = list(itervalues(doc))
IndexError: index 8 is out of bounds for size 8
```

**Comment by city-pulse** [comment]
Gensim issue.
Logging required, and adding `try...except` block.
